import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * THE REACHABILITY VERDICTS IN docs/10-dependency-risk.md, AS TESTS.
 *
 * Five advisories remain open in `npm audit` and every one is marked "not
 * reachable". Each verdict rests on a fact about today's source: there is no
 * multipart handler, there is no `next/image`, exceljs calls `uuidv4()` with no
 * arguments. Those facts are true. They are also exactly the kind of fact that
 * stops being true in a commit that has nothing to do with security, and nobody
 * re-reads a risk document when adding an avatar.
 *
 * A written verdict decays silently. That is the same defect class as a metric
 * defined in two places: two sources of truth that agree today and drift later,
 * with no alarm when they do.
 *
 * So the document does not merely assert these conditions — this file enforces
 * them. Add `next/image` and a test goes red naming the CVEs it just made live.
 * The failure message points at the doc, because the right response is usually
 * not "revert" but "re-run the analysis, this dependency now matters".
 */

const repoRoot = join(__dirname, '..', '..', '..');

/** Search tracked source only. node_modules is full of legitimate matches. */
function grepTracked(pattern: string, pathspec: string[]): string[] {
  try {
    const out = execFileSync(
      'git',
      // --untracked, because a file that is not committed yet is exactly where a
      // new next/image import lives. Without it a developer gets green locally and
      // a red CI on push, which is safe but teaches people the test is noise.
      // .gitignore is still honoured, so .next/ and node_modules/ stay out.
      ['grep', '-l', '-I', '--untracked', '--extended-regexp', pattern, '--', ...pathspec],
      { cwd: repoRoot, encoding: 'utf8' },
    );
    return out.trim().split('\n').filter(Boolean);
  } catch (e) {
    // git grep exits 1 when there are no matches. That is the passing case here,
    // and it must be distinguished from git itself failing — otherwise a broken
    // invocation reads as "clean" and every assertion below becomes vacuous.
    const err = e as { status?: number; stderr?: Buffer | string };
    if (err.status === 1) return [];
    throw new Error(`git grep failed: ${String(err.stderr ?? e)}`);
  }
}

describe('dependency reachability (docs/10-dependency-risk.md)', () => {
  it('the guard itself can find something — otherwise every test here is vacuous', () => {
    // The whole file is a set of assertions that a pattern is ABSENT. If the
    // search is silently broken, absence is what it reports no matter what is
    // in the tree. This proves the search works before trusting any "not found".
    expect(grepTracked('IngestionController', ['apps/api/src']).length).toBeGreaterThan(0);
  });

  it('sharp stays unreachable: no next/image, no image optimisation', () => {
    // sharp carries four libvips CVEs and they need a decoded attacker image.
    // It is present only as Next's image-optimisation dependency, and Next never
    // invokes it while nothing renders an optimised image.
    const users = grepTracked("from 'next/image'|<Image[ />]", [
      'apps/web',
      // Generated by Next on every build; it always references next/image-types
      // whether or not a single component uses it. Matching it would make this
      // test permanently red and therefore permanently ignored.
      ':(exclude)apps/web/next-env.d.ts',
    ]);
    expect(
      users,
      'next/image is now in use, which activates sharp and CVE-2026-33327/33328/35590/35591. ' +
        'Either upgrade sharp past 0.35.0 or re-run the analysis in docs/10-dependency-risk.md.',
    ).toEqual([]);
  });

  it('the upload path stays JSON: no multipart handler', () => {
    // Fixed already via NestJS 11, so this is not guarding a live CVE. It guards
    // the ASSUMPTION, because both the API controller and the web upload page
    // carry comments promising real multipart handling "when the widget lands" —
    // and that is the commit where multer starts mattering again.
    const handlers = grepTracked('FileInterceptor|@UploadedFile|multer[(]', ['apps/api/src', 'apps/web']);
    expect(
      handlers,
      'multipart upload handling has landed. multer is now on a live path — confirm the ' +
        'installed version is patched and update docs/10-dependency-risk.md.',
    ).toEqual([]);
  });

  it('exceljs reaches uuid only through v4, which the advisory does not cover', () => {
    // The advisory is a bounds check in v3/v5/v6 when `buf` is passed. exceljs
    // calls v4 with no arguments. Read the installed package rather than trusting
    // the note: this is the claim that justified NOT taking npm's suggested fix,
    // which was a major-version DOWNGRADE of exceljs that would break every export.
    const callSite = join(
      repoRoot,
      'node_modules/exceljs/lib/xlsx/xform/sheet/cf-ext/cf-rule-ext-xform.js',
    );
    const src = readFileSync(callSite, 'utf8');

    expect(src).toContain("const {v4: uuidv4} = require('uuid')");
    // No v3/v5/v6 import anywhere, and no call that passes an argument.
    expect(src).not.toMatch(/\b(v3|v5|v6)\b\s*:/);
    expect(src).not.toMatch(/uuidv4\([^)]+\)/);
  });

  it('we do not call uuid v3/v5/v6 ourselves', () => {
    const direct = grepTracked("require\('uuid'\)|from 'uuid'", [
      'apps',
      'packages',
      // This file quotes the pattern it searches for, so it matches itself. It
      // only passed before --untracked because it was not committed yet — an
      // accident, not a result.
      ':(exclude)apps/api/test/dependency-reachability.test.ts',
    ]);
    expect(
      direct,
      'uuid is now a direct dependency. If any call passes a `buf` to v3/v5/v6 the ' +
        'advisory becomes live and uuid must go to >= 11.1.1.',
    ).toEqual([]);
  });

  it('postcss stays unreachable: no CSS is compiled from untrusted input', () => {
    // All four postcss advisories need attacker-controlled CSS — a sourceMappingURL
    // in a comment, or an unescaped </style>. Our postcss sees our own stylesheets
    // and Tailwind's output at build time. A runtime CSS pipeline would change that.
    const runtimeCss = grepTracked(
      "require\('postcss'\)|from 'postcss'|postcss\.parse|new CleanCSS",
      ['apps/api/src', 'apps/web/app', 'apps/web/components', 'packages'],
    );
    expect(
      runtimeCss,
      'postcss is being called from application code rather than the build. If any of that ' +
        'CSS originates outside the repo, CVE path-traversal via sourceMappingURL is live.',
    ).toEqual([]);
  });

  it('the risk document still exists and names every open advisory', () => {
    // The tests above enforce the conditions; this enforces that the reasoning
    // survives alongside them. Conditions without their rationale get "fixed" by
    // deletion the first time one is inconvenient.
    const doc = readFileSync(join(repoRoot, 'docs/10-dependency-risk.md'), 'utf8');
    for (const pkg of ['uuid', 'exceljs', 'postcss', 'sharp', 'next']) {
      expect(doc, `docs/10 no longer accounts for ${pkg}`).toContain(pkg);
    }
    expect(doc).toContain('Becomes live if');
  });
});
